categories/urls.py
from django.urls import path
from . import views

app_name = "categories"
urlpatterns = [
    path('', views.categories, name="categories"),
    path('<slug:slug>/', views.category, name="category"),
]

mnryp_project/urls.py
from django.contrib import admin
from django.urls import path, include
import static_pages.views
import categories.views, categories.urls, categories.listing_urls
import search.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', static_pages.views.about, name="about"),
    path('', static_pages.views.home, name="home"),
    path('contact/', static_pages.views.contact, name="contact"),
    path('privacy_policy/', static_pages.views.privacy_policy, name="privacy_policy"),
    path('categories/', include(categories.urls)),
    path('listings/', include(categories.listing_urls)),
    path('accounts/', include('allauth.urls')),
    path('search/', search.views.search, name="search"),
]

categories/models.py
from django.db import models
from autoslug import AutoSlugField
from datetime import datetime

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    summary = models.CharField(max_length=150)
    slug = AutoSlugField(max_length=50, unique=True, populate_from='name')

    created_date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "categories"

class Listing(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    short_description = models.CharField(max_length=200)
    full_description = models.CharField(max_length=1000)
    contact_person = models.CharField(max_length=50)
    business_address = models.CharField(max_length=50)
    email_address = models.EmailField(blank=True)
    phone_number = models.CharField(max_length=10)
    phone_number_second = models.CharField(blank=True, max_length=10)
    zip_code = models.PositiveIntegerField(blank=True)
    slug = AutoSlugField(max_length=150, unique=True, populate_from='title')

    created_date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

search/models.py
from django.db import models

# Create your models here.

categories/forms.py
from django import forms
from .models import Listing

class ListingForm(forms.ModelForm):

    class Meta:
        model = Listing
        fields = ('__all__')

categories/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Category, Listing
from .forms import ListingForm
# Create your views here.

def categories(request):
    template = 'categories/categories.html'

    categories = Category.objects

    context = {
        'categories':categories,
    }
    return render(request, template, context)

def listings(request):
    template = 'categories/listings.html'

    listings = Listing.objects

    context = {
        'listings':listings,
    }
    return render(request, template, context)

def category(request, slug):
    template = 'categories/category.html'

    category = get_object_or_404(Category, slug=slug)
    listings = Listing.objects.filter(category = category)

    context = {
        'category':category,
        'listings':listings,
    }
    return render(request, template, context)

def listing(request, slug):
    template = 'categories/listing.html'

    listing = Listing.objects.filter(slug = slug)

    context = {
        'listing':listing,
    }
    return render(request, template, context)

def create_listing(request):
    template = 'categories/create_listing.html'

    if request.method == "POST":
        listing_form = ListingForm(request.POST)
        if listing_form.is_valid():
            listing_form.save()
            return redirect('listings:listings')

    else:
        listing_form = ListingForm()

    context = {
        'form':listing_form,
    }
    return render(request, template, context)

def edit_listing(request, slug):
    template = 'categories/edit_listing.html'

    listing = get_object_or_404(Listing, slug=slug)

    if request.method == "POST":
        edit_form = ListingForm(request.POST, instance=listing)
        if edit_form.is_valid():
            edit_form.save()
            return redirect('listings:listings')
    else:
        edit_form = ListingForm(instance=listing)

    context = {
        'form':edit_form,

    }
    return render(request, template, context)

def delete_listing(request, slug):
    template = 'categories/delete_listing.html'

    listing = get_object_or_404(Listing, slug=slug)

    if request.method == "POST":
        listing.delete()
        return redirect('listings:listings')

    context = {
        'listing':listing,
    }
    return render(request, template, context)

def search(request):
    template = 'categories/listings.html'

    query = request.GET.get('q')

    results = Listing.objects.filter(Q(title__icontains=query) | Q(full_description__icontains=query) | Q(short_description__icontains=query))

    context = {
        'items': results,
    }
    return render(request, template, context)

search/views.py
from django.shortcuts import render
from search.documents import ListingDocument

# Create your views here.

def search(request):
    template = 'search/search.html'

    q = request.GET.get('q')

    if q:
        listings = ListingDocument.search().query("match", title=q)
    else:
        print("no q-------------------------")
        listings = ''

    context={
        'listings': listings
    }

    print(type(listings))
    print(listings)

    return render(request, template, context)

static_pages/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    template = 'static_pages/about.html'

    return render(request, template)

def home(request):
    template = 'static_pages/home.html'

    return render(request, template)

def contact(request):
    template = 'static_pages/contact.html'

    return render(request, template)

def privacy_policy(request):
    template = 'static_pages/privacy_policy.html'

    return render(request, template)

categories/templates/categories/categories.html
{% extends 'base.html' %}

{% block content %}

<h1>This is categories page or homepage maybe</h1>

{% for category in categories.all %}

<h3>CATEGORY: <a href="{% url 'categories:category' slug=category.slug %}">{{ category.name }}</a> </h3>
<p>CATEGORY SUMMARY: {{category.summary}}</p>

{% endfor %}

<a href="{% url 'listings:listings' %}">listings</a>

{% endblock %}

categories/templates/categories/category.html
{% extends 'base.html' %}

{% block content %}

<h1>This is the category detailed view of {{ category }}</h1>

{% for listing in listings.all %}

<p><a href="{% url 'listings:listing' slug=listing.slug %}">{{ listing.title }}</a></p>
<p>{{ listing.slug }}</p>

{% endfor %}

{% endblock %}

categories/templates/categories/create_listing.html
{% extends 'base.html' %}

{% block content %}

{% load socialaccount %}
{% if user.is_authenticated %}
<h1>New listing</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">create</button>
</form>

{% else %}
<h2>You need to be logged in to create listing</h2>
<a href="{% provider_login_url 'github' %}">login/signup</a>
{% endif %}

{% endblock %}

categories/templates/categories/delete_listing.html
{% extends 'base.html' %}

{% block content %}

{% load socialaccount %}
{% if user.is_authenticated %}
<h1>delete listing</h1>
<h3>Are you sure you want to delete {{ listing.title }}</h3>
<form method="POST">
  {% csrf_token %}
  <button type="submit">delete</button>
</form>
{% else %}
<h2>Are you sure you are the author of {{ listing.title }} listing</h2>
{% endif %}

{% endblock %}

categories/templates/categories/edit_listing.html
{% extends 'base.html' %}

{% block content %}
{% load socialaccount %}
{% if user.is_authenticated %}
<h1>edit listing</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">update</button>
</form>

{% else %}
<h2>Are you sure you are the author of this listing</h2>
<a href="{% provider_login_url 'github' %}">login/signup</a>
{% endif %}

{% endblock %}

categories/templates/categories/listing.html
{% extends 'base.html' %}

{% block content %}

<h1>This is the listing detail page</h1>

{% for listing in listing.all %}
{% with listing.slug as slug %}

<h2>{{ listing.title }} || <a href="{% url 'listings:edit_listing' slug=slug %}">edit</a> || <a href="{% url 'listings:delete_listing' slug=slug %}">delete</a></h2>
<h3>{{ listing.short_description }}</h3>
<h4>{{ listing.full_description }}</h4>

{% endwith %}
{% endfor %}

{% endblock %}

categories/templates/categories/listings.html
{% extends 'base.html' %}

{% block content %}

{# search form #}
<form action="{% url 'listings:search' %}" method="GET">
  <input name="q" value="{{request.GET.q}}" placeholder="search" />
  <button class='btn btn-primary' type="submit">submit</button>
</form>

{# If search initiated #}
{% if items %}
{% for item in items.all %}
{% with item.slug as slug %}
<p>{{item}} || <a href="{% url 'listings:edit_listing' slug=slug %}">edit</a> || <a href="{% url 'listings:delete_listing' slug=slug %}">delete</a></p>
{{item.short_description}}
<br />
{{item.full_description}}
<br />
{{item.category}}
{%endwith%}
{%endfor%}
{%endif%}



<h1>This is listing page</h1>

{% for listing in listings.all %}
{% with listing.slug as slug %}

<h2><a href="{% url 'listings:listing' slug=slug %}">{{ listing.title }}</a> OR <a href="{% url 'listings:edit_listing' slug=slug %}">edit</a> OR <a href="{% url 'listings:delete_listing' slug=slug %}">delete</a></h2>
<h3>{{ listing.short_description }}</h3>
<h4>{{ listing.full_description }}</h4>
<h4>{{ listing.category }}</h4>
{% endwith %}

{% endfor %}

{% endblock %}

search/templates/search/search.html
<form method="get">
  <input type="text" name="q" id="q" placeholder="search" />
</form>
This is the object to be looped over: {{ listings }}
{% if listings.all != Null %}
{% for listing in listings.all %}
<p>{{ listing.all }}</p>
{{ listing.title }}
{{ listing.slug }}
{{ listing.short_description }}

{% endfor %}
{% else %}
but
nothing it is returning null
{% endif %}

static_pages/templates/static_pages/about.html
{% extends 'base.html' %}

{% block content %}

<h1>This is about page</h1>

{% endblock %}

static_pages/templates/static_pages/contact.html
{% extends 'base.html' %}

{% block content %}

<h1>This is contact page</h1>

{% endblock %}

static_pages/templates/static_pages/home.html
{% extends 'base.html' %}

{% block content %}

<h1>This is home page</h1>
<p><a href="categories/">categoriesl</a></p>
<p><a href="listings/">listings</a></p>

{% endblock %}

static_pages/templates/static_pages/privacy_policy.html
{% extends 'base.html' %}

{% block content %}

<h1>This is privacy policy page</h1>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>mnryp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css>' %}">
</head>

<body>
    <div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean">
            <div class="container"><a class="navbar-brand" href="#">MNR YP</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'listings:listings' %}">Listings</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'categories:categories' %}">Categories</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'listings:create_listing' %}">Create Listing</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    {% block content %}

    {% endblock %}
    
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Contact</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">MNR YP © 2019</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>


<!--        load socialaccount %}
       if user.is_authenticated %}

      <p>Welcome {{ user.username }}</p>
      <a href=" url 'account_logout' %}">logout</a>

       else %}
      <a href=" provider_login_url 'github' %}">login/signup with github</a>
      <br />
      <h4>OR</h4>
      <a href=" provider_login_url 'twitter' %}">login/signup with twitter</a> -->